# Generated by Django 3.2.4 on 2022-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela_cotas',
            fields=[
                ('odata', models.DateField(primary_key=True, serialize=False)),
                ('cotacaoCompra', models.CharField(max_length=500)),
                ('cotacaoVenda', models.CharField(max_length=500)),
            ],
        ),
    ]
